name: Rust
on: 
  push: 
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - uses: jetli/trunk-action@v0.5.0
      - uses: jetli/wasm-bindgen-action@v0.2.92
      
      - run: rustup install nightly  && rustup default nightly && rustup target add wasm32-unknown-unknown
      - uses: actions/checkout@v2

      - run: trunk build --release 

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
