name: Rust
on: 
  push: 
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - uses: jetli/trunk-action@v0.1.0
      - uses: jetli/wasm-bindgen-action@v0.1.0
      - run: rustup install nightly  && rustup target add wasm32-unknown-unknown

      - uses: actions/checkout@v2
      - run: trunk build --release --public-url /${{ github.event.repository.name }}/
